In [125]:
import numpy as np
import pandas as pd
import ast

In [126]:
movies = pd.read_csv('top_1000_popular_movies_tmdb.csv',engine = 'python')

In [127]:
movies

,Unnamed: 0,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,0,385687,Fast X,2023-05-17,"['Action', 'Crime', 'Thriller']",English,7.4,1347.0,8363.473,Over many missions and against impossible odds...,340000000.0,"['Universal Pictures', 'Original Film', 'One R...",6.520000e+08,142.0,The end of the road begins.
1,1,603692,John Wick: Chapter 4,2023-03-22,"['Action', 'Thriller', 'Crime']",English,7.9,2896.0,4210.313,"With the price on his head ever increasing, Jo...",90000000.0,"['Thunder Road', '87Eleven', 'Summit Entertain...",4.317692e+08,170.0,"No way back, one way out."
2,2,502356,The Super Mario Bros. Movie,2023-04-05,"['Animation', 'Family', 'Adventure', 'Fantasy'...",English,7.8,4628.0,3394.458,"While working underground to fix a water main,...",100000000.0,"['Universal Pictures', 'Illumination', 'Ninten...",1.308767e+09,92.0,NaN
3,3,569094,Spider-Man: Across the Spider-Verse,2023-05-31,"['Action', 'Adventure', 'Animation', 'Science ...",English,8.8,1160.0,2859.047,"After reuniting with Gwen Stacy, Brooklyn’s fu...",100000000.0,"['Columbia Pictures', 'Sony Pictures Animation...",3.135222e+08,140.0,It's how you wear the mask that matters
4,4,536437,Hypnotic,2023-05-11,"['Mystery', 'Thriller', 'Science Fiction']",English,6.5,154.0,2654.854,A detective becomes entangled in a mystery inv...,70000000.0,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0.000000e+00,94.0,Control is an illusion.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,9995,33142,Vivah,2006-11-10,"['Romance', 'Drama']",Hindi,6.4,70.0,12.301,"Poonam, a traditionally brought-up young woman...",0.0,['Rajshri Productions'],4.000000e+06,175.0,Marriage isn't a game...
9997,9996,9442,Dead Men Don't Wear Plaid,1982-05-21,"['Comedy', 'Mystery']",English,6.6,324.0,12.301,Juliet Forrest is convinced that the reported ...,9000000.0,"['Universal Pictures', 'Aspen Film Society']",1.819617e+07,89.0,Laugh...or I’ll blow your lips off!
9998,9997,28774,Communion,1989-11-10,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",English,5.3,147.0,12.300,A novelist's wife and son see him changed by a...,5000000.0,"['The Picture Property Company', 'Allied Visio...",1.919653e+06,103.0,The true story of one man's terrifying journey...
9999,9998,11121,Tess,1979-10-06,"['Drama', 'Romance']",English,7.0,283.0,12.300,A strong-willed peasant girl is sent by her fa...,12000000.0,"['Renn Productions', 'Timothy Burrill Producti...",2.010125e+07,186.0,She was born into a world where they called it...
10000,9999,272692,The Possession of Michael King,2014-08-14,['Horror'],English,6.1,346.0,12.297,The film tells the story of documentary filmma...,0.0,"['Quickfire Films', 'Gold Circle Films']",2.405143e+06,83.0,"If you invite it in, it will never let you go."

In [128]:
movies.head(1)

,Unnamed: 0,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,0,385687,Fast X,2023-05-17,"['Action', 'Crime', 'Thriller']",English,7.4,1347.0,8363.473,Over many missions and against impossible odds...,340000000.0,"['Universal Pictures', 'Original Film', 'One R...",652000000.0,142.0,The end of the road begins.

In [129]:
#required columns
#id
#genres
#overview
#tagline
#title
movies = movies[['id','title','genres','overview']]

In [130]:
movies.isna().sum()

id           0
title        0
genres       0
overview    77
dtype: int64

In [131]:
movies = movies.dropna()

In [132]:
movies.duplicated().sum()

np.int64(0)

In [133]:
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i.replace(" ", ""))
    return l

In [134]:
movies['genres'] = movies['genres'].apply(convert)

In [135]:
movies.head()

,id,title,genres,overview
0,385687,Fast X,"[Action, Crime, Thriller]",Over many missions and against impossible odds...
1,603692,John Wick: Chapter 4,"[Action, Thriller, Crime]","With the price on his head ever increasing, Jo..."
2,502356,The Super Mario Bros. Movie,"[Animation, Family, Adventure, Fantasy, Comedy]","While working underground to fix a water main,..."
3,569094,Spider-Man: Across the Spider-Verse,"[Action, Adventure, Animation, ScienceFiction]","After reuniting with Gwen Stacy, Brooklyn’s fu..."
4,536437,Hypnotic,"[Mystery, Thriller, ScienceFiction]",A detective becomes entangled in a mystery inv...

In [136]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [137]:
movies.head()

,id,title,genres,overview
0,385687,Fast X,"[Action, Crime, Thriller]","[Over, many, missions, and, against, impossibl..."
1,603692,John Wick: Chapter 4,"[Action, Thriller, Crime]","[With, the, price, on, his, head, ever, increa..."
2,502356,The Super Mario Bros. Movie,"[Animation, Family, Adventure, Fantasy, Comedy]","[While, working, underground, to, fix, a, wate..."
3,569094,Spider-Man: Across the Spider-Verse,"[Action, Adventure, Animation, ScienceFiction]","[After, reuniting, with, Gwen, Stacy,, Brookly..."
4,536437,Hypnotic,"[Mystery, Thriller, ScienceFiction]","[A, detective, becomes, entangled, in, a, myst..."

In [138]:
movies['tags'] = movies['genres'] + movies['overview']

In [139]:
movies.head()

,id,title,genres,overview,tags
0,385687,Fast X,"[Action, Crime, Thriller]","[Over, many, missions, and, against, impossibl...","[Action, Crime, Thriller, Over, many, missions..."
1,603692,John Wick: Chapter 4,"[Action, Thriller, Crime]","[With, the, price, on, his, head, ever, increa...","[Action, Thriller, Crime, With, the, price, on..."
2,502356,The Super Mario Bros. Movie,"[Animation, Family, Adventure, Fantasy, Comedy]","[While, working, underground, to, fix, a, wate...","[Animation, Family, Adventure, Fantasy, Comedy..."
3,569094,Spider-Man: Across the Spider-Verse,"[Action, Adventure, Animation, ScienceFiction]","[After, reuniting, with, Gwen, Stacy,, Brookly...","[Action, Adventure, Animation, ScienceFiction,..."
4,536437,Hypnotic,"[Mystery, Thriller, ScienceFiction]","[A, detective, becomes, entangled, in, a, myst...","[Mystery, Thriller, ScienceFiction, A, detecti..."

In [140]:
movies.shape

(9924, 5)

In [141]:
new_df = movies[['id','title','tags']]

In [142]:
new_df.shape

(9924, 3)

In [143]:
new_df['tags'][0]

['Action',
 'Crime',
 'Thriller',
 'Over',
 'many',
 'missions',
 'and',
 'against',
 'impossible',
 'odds,',
 'Dom',
 'Toretto',
 'and',
 'his',
 'family',
 'have',
 'outsmarted,',
 'out-nerved',
 'and',
 'outdriven',
 'every',
 'foe',
 'in',
 'their',
 'path.',
 'Now,',
 'they',
 'confront',
 'the',
 'most',
 'lethal',
 'opponent',
 "they've",
 'ever',
 'faced:',
 'A',
 'terrifying',
 'threat',
 'emerging',
 'from',
 'the',
 'shadows',
 'of',
 'the',
 'past',
 "who's",
 'fueled',
 'by',
 'blood',
 'revenge,',
 'and',
 'who',
 'is',
 'determined',
 'to',
 'shatter',
 'this',
 'family',
 'and',
 'destroy',
 'everything—and',
 'everyone—that',
 'Dom',
 'loves,',
 'forever.']

In [144]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Surya Teja\AppData\Local\Temp\ipykernel_4724\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [145]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\Surya Teja\AppData\Local\Temp\ipykernel_4724\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [146]:
new_df

,id,title,tags
0,385687,Fast X,action crime thriller over many missions and a...
1,603692,John Wick: Chapter 4,action thriller crime with the price on his he...
2,502356,The Super Mario Bros. Movie,animation family adventure fantasy comedy whil...
3,569094,Spider-Man: Across the Spider-Verse,action adventure animation sciencefiction afte...
4,536437,Hypnotic,mystery thriller sciencefiction a detective be...
...,...,...,...
9996,33142,Vivah,"romance drama poonam, a traditionally brought-..."
9997,9442,Dead Men Don't Wear Plaid,comedy mystery juliet forrest is convinced tha...
9998,28774,Communion,drama horror sciencefiction thriller a novelis...
9999,11121,Tess,drama romance a strong-willed peasant girl is ...
10000,272692,The Possession of Michael King,horror the film tells the story of documentary...

In [147]:
import nltk

In [148]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [149]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [150]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Surya Teja\AppData\Local\Temp\ipykernel_4724\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [151]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [152]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [153]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [154]:
print(cv.get_feature_names_out())

['000' '10' '100' ... 'zombies' 'zone' 'zoo']

In [155]:
from sklearn.metrics.pairwise import cosine_similarity

In [156]:
similarity = cosine_similarity(vectors)

In [157]:
similarity

array([[1.        , 0.17716158, 0.06448259, ..., 0.0474579 , 0.07974522,
        0.03958262],
       [0.17716158, 1.        , 0.0352235 , ..., 0.05184758, 0.        ,
        0.10810969],
       [0.06448259, 0.0352235 , 1.        , ..., 0.        , 0.04756515,
        0.        ],
       ...,
       [0.0474579 , 0.05184758, 0.        , ..., 1.        , 0.070014  ,
        0.0695048 ],
       [0.07974522, 0.        , 0.04756515, ..., 0.070014  , 1.        ,
        0.        ],
       [0.03958262, 0.10810969, 0.        , ..., 0.0695048 , 0.        ,
        1.        ]])

In [158]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [159]:
recommend('Spider-Man: Across the Spider-Verse')

Spider-Man: Into the Spider-Verse
Spider-Man: Beyond the Spider-Verse
Spider-Man: The Mythology of the 21st Century
Spider-Man 4
Spider-Man 3

In [160]:
new_df.to_dict()

{'id': {0: 385687,
  1: 603692,
  2: 502356,
  3: 569094,
  4: 536437,
  5: 667538,
  6: 890771,
  7: 447277,
  8: 76600,
  9: 713704,
  10: 1018494,
  11: 447365,
  12: 1010581,
  13: 640146,
  14: 840326,
  15: 879444,
  16: 758323,
  17: 1073140,
  18: 1107872,
  19: 1098110,
  20: 799379,
  21: 605886,
  22: 882569,
  23: 1115710,
  24: 324857,
  25: 594767,
  26: 677179,
  27: 1077321,
  28: 1074178,
  29: 620705,
  30: 1070777,
  31: 552688,
  32: 315162,
  33: 1105803,
  34: 842675,
  35: 893712,
  36: 931102,
  37: 298618,
  38: 976912,
  39: 934433,
  40: 868759,
  41: 943930,
  42: 420808,
  43: 981324,
  44: 1094319,
  45: 1074034,
  46: 634649,
  47: 1064517,
  48: 1118203,
  49: 91314,
  50: 505642,
  51: 436270,
  52: 916224,
  53: 493529,
  54: 977866,
  55: 948713,
  56: 638974,
  57: 1098160,
  58: 8869,
  59: 977223,
  60: 816904,
  61: 1102776,
  62: 1109207,
  63: 649609,
  64: 335988,
  65: 1020696,
  66: 1014501,
  67: 1094403,
  68: 736790,
  69: 702621,
  70: 804150,
  71: 507250,
  72: 995012,
  73: 1016121,
  74: 1037644,
  75: 1121116,
  76: 536554,
  77: 1033219,
  78: 25565,
  79: 914827,
  80: 980078,
  81: 646389,
  82: 19995,
  83: 976573,
  84: 911916,
  85: 10144,
  86: 700391,
  87: 985939,
  88: 809787,
  89: 727340,
  90: 946310,
  91: 1126852,
  92: 1008005,
  93: 876969,
  94: 663712,
  95: 785759,
  96: 997776,
  97: 507086,
  98: 675353,
  99: 631842,
  100: 361743,
  101: 1041513,
  102: 876792,
  103: 616037,
  104: 803700,
  105: 758009,
  106: 785084,
  107: 283995,
  108: 668482,
  109: 697843,
  110: 962682,
  111: 1119173,
  112: 724495,
  113: 842945,
  114: 296271,
  115: 943788,
  116: 960081,
  117: 869626,
  118: 381284,
  119: 943822,
  120: 1003579,
  121: 453395,
  122: 1127227,
  123: 568124,
  124: 508947,
  125: 414906,
  126: 766507,
  127: 411,
  128: 1111140,
  129: 299536,
  130: 585511,
  131: 776835,
  132: 966220,
  133: 1129692,
  134: 758336,
  135: 325358,
  136: 579884,
  137: 635302,
  138: 744276,
  139: 385128,
  140: 438148,
  141: 455476,
  142: 682507,
  143: 875104,
  144: 384018,
  145: 676710,
  146: 676547,
  147: 1048300,
  148: 458220,
  149: 820232,
  150: 102382,
  151: 265712,
  152: 1011679,
  153: 1013860,
  154: 1103510,
  155: 988233,
  156: 1123342,
  157: 842544,
  158: 723347,
  159: 1084225,
  160: 843794,
  161: 736526,
  162: 646385,
  163: 296096,
  164: 324552,
  165: 970284,
  166: 829560,
  167: 458156,
  168: 920125,
  169: 845659,
  170: 1077280,
  171: 1023313,
  172: 315635,
  173: 573171,
  174: 615656,
  175: 947938,
  176: 580489,
  177: 671,
  178: 168259,
  179: 438695,
  180: 381288,
  181: 516806,
  182: 551271,
  183: 346698,
  184: 1858,
  185: 1016084,
  186: 1121316,
  187: 49046,
  188: 537915,
  189: 672,
  190: 557,
  191: 585083,
  192: 345940,
  193: 874745,
  194: 673,
  195: 846433,
  196: 555604,
  197: 829557,
  198: 1045944,
  199: 324786,
  200: 575322,
  201: 674,
  202: 1104040,
  203: 791373,
  204: 337339,
  205: 13962,
  206: 1003580,
  207: 882598,
  208: 760741,
  209: 964980,
  210: 545609,
  211: 868985,
  212: 532408,
  213: 1076605,
  214: 1058732,
  215: 818647,
  216: 1085103,
  217: 12445,
  218: 157336,
  219: 335787,
  220: 767,
  221: 790496,
  222: 1079078,
  223: 718930,
  224: 68718,
  225: 619329,
  227: 550988,
  228: 385448,
  229: 643215,
  230: 1105014,
  231: 820067,
  232: 874743,
  233: 601796,
  234: 755679,
  235: 960258,
  236: 1930,
  237: 851644,
  238: 76203,
  239: 830784,
  240: 899112,
  241: 429617,
  242: 1026563,
  243: 230622,
  244: 760204,
  245: 12444,
  246: 774752,
  247: 338953,
  248: 937278,
  249: 338958,
  250: 717728,
  251: 744275,
  252: 599019,
  253: 925341,
  254: 884605,
  255: 597,
  256: 884184,
  257: 566525,
  258: 873126,
  259: 675,
  260: 585,
  261: 613504,
  262: 947704,
  263: 760104,
  264: 884535,
  265: 496450,
  266: 653851,
  267: 482600,
  268: 877269,
  269: 539681,
  270: 985617,
  271: 983105,
  272: 823999,
  273: 406759,
  274: 850871,
  275: 940241,
  276: 24428,
  277: 982271,
  278: 81774,
  279: 216015,
  280: 984105,
  281: 808,
  282: 424783,
  283: 238,
  284: 232672,
  285: 916283,
  286: 849869,
  287: 732459,
  288: 337404,
  289: 774825,
  290: 55685,
  291: 579974,
  292: 1035806,
  293: 961718,
  294: 1126844,
  295: 198663,
  296: 335977,
  297: 772515,
  298: 74308,
  299: 752623,
  300: 560821,
  301: 460465,
  302: 311324,
  303: 642885,
  304: 795514,
  305: 399566,
  306: 792775,
  307: 1093349,
  308: 848058,
  309: 338947,
  310: 1087771,
  311: 836225,
  312: 354912,
  313: 842942,
  314: 337167,
  315: 862,
  316: 960704,
  317: 614479,
  318: 508943,
  319: 988165,
  320: 290271,
  321: 1058949,
  322: 779782,
  323: 207703,
  324: 1046064,
  325: 559,
  326: 1865,
  327: 988078,
  328: 916712,
  329: 955991,
  330: 14836,
  331: 8587,
  332: 916605,
  333: 22803,
  334: 38757,
  335: 299534,
  336: 1128568,
  337: 852046,
  338: 965839,
  339: 756999,
  340: 9453,
  341: 1037858,
  342: 675445,
  343: 698687,
  344: 476669,
  345: 450465,
  346: 327753,
  347: 1015957,
  348: 939210,
  349: 931954,
  350: 760161,
  351: 2062,
  352: 718789,
  353: 610150,
  354: 751741,
  355: 106,
  356: 50014,
  357: 106646,
  358: 912726,
  359: 420634,
  360: 512195,
  361: 459151,
  362: 924482,
  363: 755812,
  364: 293660,
  365: 438631,
  366: 869612,
  367: 118340,
  368: 1018403,
  369: 615777,
  370: 526896,
  371: 559682,
  372: 1003813,
  373: 436969,
  374: 809,
  375: 983768,
  376: 1087040,
  377: 676701,
  378: 639933,
  379: 950141,
  380: 460458,
  381: 22,
  382: 27449,
  383: 1119749,
  384: 14160,
  385: 860623,
  386: 801071,
  387: 739405,
  388: 37165,
  389: 404250,
  390: 524434,
  391: 285,
  392: 629176,
  393: 330457,
  394: 99861,
  395: 107406,
  396: 480530,
  397: 981344,
  398: 994128,
  399: 585245,
  400: 423108,
  401: 447362,
  402: 420818,
  403: 425,
  404: 245891,
  405: 177572,
  406: 1024546,
  407: 626872,
  408: 20982,
  409: 650270,
  410: 1116875,
  411: 955555,
  412: 303857,
  413: 588228,
  414: 18785,
  415: 10198,
  416: 726684,
  417: 979924,
  418: 676841,
  419: 120,
  420: 10674,
  421: 312221,
  422: 343668,
  423: 661374,
  424: 27205,
  425: 228150,
  426: 837938,
  427: 906221,
  428: 996727,
  429: 113082,
  430: 11688,
  431: 155,
  432: 637649,
  433: 726366,
  434: 9820,
  435: 529203,
  436: 801335,
  437: 339846,
  438: 156022,
  439: 624860,
  440: 629542,
  441: 497698,
  442: 372058,
  443: 39323,
  444: 826753,
  445: 782936,
  446: 138843,
  447: 58,
  448: 946700,
  449: 880841,
  450: 810693,
  451: 518896,
  452: 49013,
  453: 829410,
  454: 8373,
  455: 109418,
  456: 150540,
  457: 527774,
  458: 953,
  459: 545611,
  460: 10138,
  461: 118412,
  462: 264859,
  463: 12,
  464: 131631,
  465: 49018,
  466: 23823,
  467: 717930,
  468: 1114905,
  469: 8966,
  470: 146233,
  471: 118,
  472: 383498,
  473: 260513,
  474: 242562,
  475: 425909,
  476: 61979,
  477: 818397,
  478: 4247,
  479: 810,
  480: 728754,
  481: 370172,
  482: 960700,
  483: 39108,
  484: 474350,
  485: 762504,
  486: 10192,
  487: 150689,
  488: 872516,
  489: 790409,
  490: 803694,
  491: 193893,
  492: 877703,
  493: 34433,
  494: 72190,
  495: 260514,
  496: 122917,
  497: 497,
  498: 11224,
  499: 75338,
  500: 589754,
  501: 628900,
  502: 254128,
  503: 878361,
  504: 7445,
  505: 863,
  506: 121,
  507: 109445,
  508: 508442,
  509: 59053,
  510: 987578,
  511: 931935,
  512: 114,
  513: 102651,
  514: 668461,
  515: 497828,
  516: 626735,
  517: 964426,
  518: 982620,
  519: 1726,
  520: 943221,
  521: 862965,
  522: 87101,
  523: 191561,
  524: 583055,
  525: 501170,
  526: 791155,
  527: 10195,
  528: 919355,
  529: 280,
  530: 1024530,
  531: 38365,
  532: 122,
  533: 39254,
  534: 987750,
  535: 379686,
  536: 1007401,
  537: 11,
  538: 267805,
  539: 783675,
  540: 348893,
  541: 961484,
  542: 634528,
  543: 916719,
  544: 740952,
  545: 560057,
  546: 135397,
  547: 49521,
  548: 555285,
  549: 45243,
  550: 98566,
  551: 214756,
  552: 773867,
  553: 705996,
  554: 284052,
  555: 16270,
  556: 928773,
  557: 451048,
  558: 284053,
  559: 257344,
  560: 675054,
  561: 520763,
  562: 526811,
  563: 271110,
  564: 1118721,
  565: 68726,
  566: 619730,
  567: 400160,
  568: 821890,
  569: 879538,
  570: 575264,
  571: 45288,
  572: 49530,
  573: 439079,
  574: 10020,
  575: 1040148,
  576: 744,
  577: 454626,
  578: 287947,
  579: 13186,
  580: 811656,
  581: 667739,
  582: 278,
  583: 615457,
  584: 945675,
  585: 1030613,
  586: 803114,
  587: 67308,
  588: 829799,
  589: 630586,
  590: 855440,
  591: 928123,
  592: 408,
  593: 511617,
  594: 921785,
  595: 60898,
  596: 512200,
  597: 683328,
  598: 4935,
  599: 813726,
  600: 44251,
  601: 642271,
  602: 112355,
  603: 1008640,
  604: 141052,
  605: 532639,
  606: 961651,
  607: 800815,
  608: 499338,
  609: 812,
  610: 12153,
  611: 197,
  612: 603,
  613: 345887,
  614: 8355,
  615: 335795,
  616: 85,
  617: 335983,
  618: 616820,
  619: 87584,
  620: 556694,
  621: 531219,
  622: 507089,
  623: 929170,
  624: 790416,
  625: 527776,
  626: 129,
  627: 901563,
  628: 20352,
  629: 269149,
  630: 640,
  631: 829165,
  632: 272878,
  633: 1047431,
  634: 1013870,
  635: 9288,
  636: 511817,
  637: 900667,
  638: 725201,
  639: 9741,
  640: 49051,
  641: 205596,
  642: 400928,
  643: 626332,
  644: 86331,
  645: 109689,
  646: 11970,
  647: 615173,
  648: 4248,
  649: 16869,
  651: 948276,
  652: 1001835,
  653: 93456,
  654: 76341,
  655: 993621,
  656: 550,
  657: 475557,
  658: 1127209,
  659: 1073413,
  660: 561,
  661: 1104191,
  662: 1122493,
  663: 811592,
  664: 856245,
  665: 9806,
  666: 4232,
  667: 321612,
  668: 464052,
  669: 73723,
  670: 270946,
  671: 218,
  672: 828558,
  673: 82386,
  674: 317442,
  675: 298191,
  676: 38356,
  677: 602223,
  678: 45453,
  679: 841,
  680: 639721,
  681: 1010818,
  682: 913673,
  683: 1015602,
  684: 71672,
  685: 897192,
  686: 375794,
  687: 10193,
  688: 420809,
  689: 4258,
  690: 840789,
  691: 934641,
  692: 878183,
  693: 581726,
  694: 938008,
  695: 50646,
  696: 1082010,
  697: 829280,
  698: 927085,
  699: 9479,
  700: 37135,
  701: 83088,
  702: 13,
  703: 335984,
  704: 886396,
  705: 297,
  706: 9502,
  707: 778552,
  708: 166428,
  709: 1012404,
  710: 38575,
  711: 8920,
  712: 1001865,
  713: 679,
  714: 1015724,
  715: 800345,
  716: 109439,
  717: 68721,
  718: 38234,
  719: 1094643,
  720: 1012801,
  721: 429473,
  722: 942199,
  723: 482373,
  724: 259693,
  725: 697251,
  726: 830788,
  727: 297270,
  728: 607259,
  729: 593643,
  730: 24021,
  731: 77338,
  732: 11969,
  733: 759175,
  734: 458576,
  735: 323260,
  736: 62211,
  737: 942922,
  738: 210577,
  739: 833425,
  740: 14869,
  741: 337401,
  742: 62177,
  743: 680,
  744: 1366,
  745: 274855,
  746: 554596,
  747: 523931,
  748: 899082,
  749: 696806,
  750: 800301,
  751: 297802,
  752: 1025169,
  753: 10681,
  754: 235331,
  755: 166426,
  756: 125509,
  757: 57800,
  758: 587807,
  759: 76338,
  760: 788752,
  761: 146368,
  762: 105905,
  763: 768362,
  764: 12429,
  765: 109428,
  766: 91586,
  767: 747188,
  768: 949423,
  769: 256591,
  770: 936621,
  771: 934287,
  772: 49026,
  773: 812225,
  774: 564,
  775: 496243,
  776: 268896,
  777: 7980,
  778: 826942,
  779: 82690,
  780: 9487,
  781: 301528,
  782: 209112,
  783: 9902,
  784: 75780,
  785: 11036,
  786: 589752,
  787: 260346,
  788: 522924,
  789: 66105,
  790: 7485,
  791: 1023803,
  792: 32657,
  793: 652,
  794: 872177,
  795: 406563,
  796: 1724,
  797: 1824,
  798: 581528,
  799: 823625,
  800: 578,
  801: 807356,
  802: 829503,
  803: 111,
  804: 736759,
  805: 190859,
  806: 913290,
  807: 39107,
  808: 348,
  809: 420821,
  810: 9023,
  811: 983282,
  812: 1857,
  813: 899579,
  814: 1120558,
  815: 370663,
  816: 329865,
  817: 6479,
  818: 12155,
  819: 958196,
  820: 807,
  821: 333339,
  822: 481871,
  823: 14161,
  824: 35,
  825: 1063242,
  826: 950,
  827: 763285,
  828: 568620,
  829: 892527,
  830: 75258,
  831: 9732,
  832: 351286,
  833: 876797,
  834: 119450,
  835: 637693,
  836: 800937,
  837: 240,
  838: 27098,
  839: 764,
  840: 82023,
  841: 406990,
  842: 971530,
  843: 57214,
  844: 333167,
  845: 534179,
  846: 495764,
  847: 589761,
  848: 1101799,
  849: 346364,
  850: 126963,
  851: 482321,
  852: 989473,
  853: 47971,
  854: 4233,
  855: 263115,
  856: 353081,
  857: 11544,
  858: 102899,
  859: 929562,
  860: 44918,
  861: 8363,
  862: 86328,
  863: 420817,
  864: 198184,
  865: 286687,
  867: 755566,
  868: 243352,
  869: 1010821,
  870: 37024,
  871: 105,
  872: 41446,
  873: 335797,
  874: 1049233,
  875: 353440,
  876: 359724,
  877: 39145,
  878: 373571,
  879: 72559,
  880: 1006851,
  881: 287590,
  882: 228088,
  883: 608236,
  884: 662708,
  885: 124905,
  886: 50619,
  887: 9325,
  888: 12092,
  889: 50620,
  890: 225886,
  891: 877183,
  892: 294254,
  893: 244786,
  894: 37021,
  895: 396535,
  896: 350,
  897: 660982,
  898: 557950,
  899: 1040603,
  900: 928015,
  901: 768744,
  902: 921360,
  903: 1076443,
  904: 299054,
  905: 280092,
  906: 98,
  907: 521029,
  908: 299537,
  909: 341174,
  910: 522402,
  911: 353486,
  912: 184345,
  913: 619803,
  914: 864370,
  915: 49519,
  916: 366672,
  917: 75624,
  918: 297762,
  919: 846778,
  920: 577922,
  921: 13811,
  922: 3933,
  923: 398818,
  924: 345938,
  925: 18240,
  926: 710356,
  927: 74887,
  928: 268,
  929: 703771,
  930: 615,
  931: 857,
  932: 72545,
  933: 542196,
  934: 985932,
  935: 343611,
  936: 10625,
  937: 615469,
  938: 417859,
  939: 632357,
  940: 101299,
  941: 631843,
  942: 550205,
  943: 9552,
  944: 407439,
  945: 138832,
  946: 8681,
  947: 70981,
  948: 390845,
  949: 246655,
  950: 630,
  951: 27578,
  952: 9637,
  953: 746524,
  954: 87,
  955: 138103,
  956: 879990,
  957: 887379,
  958: 411088,
  959: 588108,
  960: 386716,
  961: 89,
  962: 10567,
  963: 83090,
  964: 1065890,
  965: 210726,
  966: 490132,
  967: 39106,
  968: 883083,
  969: 18,
  970: 2109,
  971: 576925,
  972: 14128,
  973: 57158,
  974: 818422,
  975: 126889,
  976: 49444,
  977: 13688,
  978: 284054,
  979: 307081,
  980: 127585,
  981: 726759,
  982: 607,
  983: 1027159,
  984: 82702,
  985: 926899,
  986: 24752,
  987: 762975,
  988: 546554,
  989: 346910,
  990: 197158,
  991: 4705,
  992: 926393,
  993: 493922,
  994: 55580,
  995: 363088,
  996: 290859,
  997: 1120628,
  998: 378064,
  999: 105864,
  1000: 183011,
  1001: 723072,
  1002: 38700,
  ...},
 'title': {0: 'Fast X',
  1: 'John Wick: Chapter 4',
  2: 'The Super Mario Bros. Movie',
  3: 'Spider-Man: Across the Spider-Verse',
  4: 'Hypnotic',
  5: 'Transformers: Rise of the Beasts',
  6: 'The Black Demon',
  7: 'The Little Mermaid',
  8: 'Avatar: The Way of Water',
  9: 'Evil Dead Rise',
  10: 'Operation Seawolf',
  11: 'Guardians of the Galaxy Vol. 3',
  12: 'My Fault',
  13: 'Ant-Man and the Wasp: Quantumania',
  14: 'Sisu',
  15: "Accident Man: Hitman's Holiday",
  16: "The Pope's Exorcist",
  17: 'The Three Musketeers',
  18: "Mother's Day",
  19: 'Blood & Gold',
  20: 'Project Wolf Hunting',
  21: 'To Catch a Killer',
  22: "Guy Ritchie's The Covenant",
  23: 'The Mount 2',
  24: 'Spider-Man: Into the Spider-Verse',
  25: 'Shazam! Fury of the Gods',
  26: 'Creed III',
  27: 'Drunken Fist',
  28: 'Extras For Chasing The Dragon',
  29: 'Crater',
  30: 'One Day as a Lion',
  31: 'The Mother',
  32: 'Puss in Boots: The Last Wish',
  33: 'Snag',
  34: 'The Wandering Earth II',
  35: 'Sword Art Online the Movie -Progressive- Scherzo of Deep Night',
  36: 'Ride On',
  37: 'The Flash',
  38: 'Graphic Desires',
  39: 'Scream VI',
  40: 'Ghosted',
  41: 'Tin & Tina',
  42: 'Peter Pan & Wendy',
  43: 'Island of the Dolls',
  44: 'The Best Man',
  45: 'Ambush',
  46: 'Spider-Man: No Way Home',
  47: 'Fist of the Condor',
  48: 'The Swan Princess: A Fairytale Is Born',
  49: 'Transformers: Age of Extinction',
  50: 'Black Panther: Wakanda Forever',
  51: 'Black Adam',
  52: 'Suzume',
  53: 'Dungeons & Dragons: Honor Among Thieves',
  54: 'The Ghosts of Monday',
  55: 'The Last Kingdom: Seven Kings Must Die',
  56: 'Murder Mystery 2',
  57: 'The Tank',
  58: 'Eight Legged Freaks',
  59: 'Polite Society',
  60: 'Mummies',
  61: 'AKA',
  62: 'Taz: Quest for Burger',
  63: 'Renfield',
  64: 'Transformers: The Last Knight',
  65: 'Play Dead',
  66: 'Grotesque',
  67: 'Malum',
  68: 'Chupa',
  69: 'Lullaby',
  70: 'Cocaine Bear',
  71: 'Dead Shot',
  72: 'The Tutor',
  73: 'Beautiful Disaster',
  74: 'Battle for Saipan',
  75: 'Maggie Simpson in "Rogue Not Quite One"',
  76: 'M3GAN',
  77: 'Attack on Titan',
  78: 'Transformers: Beginnings',
  79: 'Dangerous Snow Day',
  80: 'Winnie the Pooh: Blood and Honey',
  81: 'Plane',
  82: 'Avatar',
  83: 'Elemental',
  84: 'Spider-Man: Beyond the Spider-Verse',
  85: 'The Little Mermaid',
  86: '65',
  87: 'Fall',
  88: 'Mafia Mamma',
  89: 'Hunt',
  90: 'Pirates Down the Street II: The Ninjas from Across',
  91: 'Rich in Love 2',
  92: 'The Communion Girl',
  93: 'Assassin Club',
  94: 'Terrifier 2',
  95: 'Two Witches',
  96: 'Justice League x RWBY: Super Heroes & Huntsmen, Part One',
  97: 'Jurassic World Dominion',
  98: 'Sonic the Hedgehog 2',
  99: 'Knock at the Cabin',
  100: 'Top Gun: Maverick',
  101: 'Encanto at the Hollywood Bowl',
  102: 'That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond',
  103: 'Thor: Love and Thunder',
  104: 'The Eight Mountains',
  105: 'Shotgun Wedding',
  106: 'The Whale',
  107: 'Guardians of the Galaxy Vol. 2',
  108: "Roald Dahl's Matilda the Musical",
  109: 'Extraction 2',
  110: 'An Unforgettable Year: Summer',
  111: 'A Beautiful Life',
  112: 'The Woman King',
  113: 'Supercell',
  114: 'The Devil Conspiracy',
  115: 'From Black',
  116: 'Surrogate',
  117: 'Marcel the Shell with Shoes On',
  118: 'Hidden Figures',
  119: 'Prizefighter: The Life of Jem Belcher',
  120: 'Batman: The Doom That Came to Gotham',
  121: 'Doctor Strange in the Multiverse of Madness',
  122: 'Tayuan',
  123: 'Encanto',
  124: 'Turning Red',
  125: 'The Batman',
  126: 'Prey',
  127: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  128: 'Two Sinners and a Mule',
  129: 'Avengers: Infinity War',
  130: 'Luck',
  131: "The Magician's Elephant",
  132: 'Sniper: The White Raven',
  133: 'Lego Friends: The Next Chapter: New Beginnings',
  134: 'Love Again',
  135: 'Superfast!',
  136: 'The Swiss Adventure',
  137: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
  138: 'After Ever Happy',
  139: 'F9',
  140: 'Minions: The Rise of Gru',
  141: 'Knights of the Zodiac',
  142: 'Where the Crawdads Sing',
  143: 'Ip Man: The Awakening',
  144: 'Fast & Furious Presents: Hobbs & Shaw',
  145: 'The Amazing Maurice',
  146: 'Prey for the Devil',
  147: 'Adrenaline',
  148: 'Palmer',
  149: "Demon Slayer: Kimetsu no Yaiba Sibling's Bond",
  150: 'The Amazing Spider-Man 2',
  151: 'Stand by Me Doraemon',
  152: 'Shark Side of the Moon',
  153: 'R.I.P.D. 2: Rise of the Damned',
  154: 'Rooming With Danger',
  155: 'Hex',
  156: 'Missed Connections',
  157: 'Transfusion',
  158: 'Robots',
  159: 'The Park',
  160: 'JUNG_E',
  161: 'Troll',
  162: 'Scream',
  163: 'Me Before You',
  164: 'John Wick: Chapter 2',
  165: 'Shooting Stars',
  166: 'The Next 365 Days',
  167: 'John Wick: Chapter 3 - Parabellum',
  168: "White Men Can't Jump",
  169: 'Perfect Addiction',
  170: 'Die Hart',
  171: 'The Exorcist',
  172: 'Spider-Man: Homecoming',
  173: 'A Frozen Rooster',
  174: 'Meg 2: The Trench',
  175: 'Dolphin Boy',
  176: 'Venom: Let There Be Carnage',
  177: "Harry Potter and the Philosopher's Stone",
  178: 'Furious 7',
  179: 'Sing 2',
  180: 'Split',
  181: 'Last Sentinel',
  182: 'Medieval',
  183: 'Barbie',
  184: 'Transformers',
  185: 'BlackBerry',
  186: 'Where the Tracks End',
  187: 'All Quiet on the Western Front',
  188: 'After',

In [161]:
import pickle

In [162]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [163]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [164]:
new_df.shape

(9924, 3)